import { FormField, TableColumn } from '../../core/models/common.models';
import { keysToOptions } from '../../shared/crud/options';

export const PRODUCTION_ORDER_COLUMNS: TableColumn[] = [
  { key: 'number', labelKey: 'common.number' },
  { key: 'date', labelKey: 'common.date', type: 'date' },
  { key: 'workOrderNumber', labelKey: 'production.fields.workOrder' },
  { key: 'specName', labelKey: 'production.fields.spec', multilang: true },
  { key: 'productName', labelKey: 'qc.fields.productName' },
  { key: 'mixType', labelKey: 'qc.fields.mixType', type: 'key' },
  { key: 'parentFamily', labelKey: 'qc.fields.parent' },
  { key: 'ply', labelKey: 'qc.fields.ply', align: 'center' },
  { key: 'color', labelKey: 'qc.fields.color', type: 'key' },
  { key: 'gsm', labelKey: 'cutter.label.gsm', type: 'number', align: 'center' },
  { key: 'widthMm', labelKey: 'qc.fields.width', type: 'number', align: 'center' },
  { key: 'quantityKg', labelKey: 'common.quantity', type: 'number' },
  { key: 'producedKg', labelKey: 'production.fields.produced', type: 'number' },
  { key: 'wastePercent', labelKey: 'production.fields.waste', type: 'number', align: 'center' },
  { key: 'rollsProduced', labelKey: 'production.fields.rollsProduced', type: 'number', align: 'center' },
  { key: 'rollsTarget', labelKey: 'production.fields.rollsTarget', type: 'number', align: 'center' },
  { key: 'expectedFinish', labelKey: 'production.fields.expectedFinish', type: 'date' },
  {
    key: 'autoCreated',
    labelKey: 'production.fields.autoCreated',
    type: 'badge',
    keyPrefix: 'production.auto.',
    badgeToneMap: { true: 'info', false: 'neutral' },
  },
  {
    key: 'sourceType',
    labelKey: 'production.fields.source',
    type: 'badge',
    keyPrefix: 'production.sources.',
    badgeToneMap: {
      'work-order': 'info',
      'export-order': 'warning',
      'manual': 'neutral',
    },
  },
  {
    key: 'status',
    labelKey: 'common.status',
    type: 'badge',
    statusFlow: ['open', 'in-progress', 'completed'],
    keyPrefix: 'production.status.',
    badgeToneMap: {
      'open': 'info',
      'in-progress': 'warning',
      'completed': 'success',
      'late': 'danger',
      'stopped': 'danger',
    },
  },
  {
    key: 'approvalStatus',
    labelKey: 'production.fields.approvalStatus',
    type: 'badge',
    statusFlow: ['pending', 'approved', 'rejected'],
    statusNeed: {
      approved: { key: 'scheduledDate', labelKey: 'production.fields.scheduledDate' },
    },
    keyPrefix: 'production.approval.',
    badgeToneMap: {
      'pending': 'warning',
      'approved': 'success',
      'rejected': 'danger',
    },
  },
  { key: 'scheduledDate', labelKey: 'production.fields.scheduledDate', type: 'date' },
  { key: 'rescheduleDate', labelKey: 'production.fields.rescheduleDate', type: 'date' },
  {
    key: 'rescheduleStatus',
    labelKey: 'production.fields.rescheduleStatus',
    type: 'badge',
    statusFlow: ['pending', 'approved', 'rejected'],
    keyPrefix: 'production.reschedule.',
    badgeToneMap: {
      'pending': 'warning',
      'approved': 'success',
      'rejected': 'danger',
    },
  },
];

export const PRODUCTION_ORDER_FIELDS: FormField[] = [
  { key: 'number', labelKey: 'common.number', generated: true, generatedPrefix: 'MO' },
  { key: 'date', labelKey: 'common.date', type: 'date' },
  { key: 'workOrderNumber', labelKey: 'production.fields.workOrder' },
  { key: 'specName', labelKey: 'production.fields.spec', multilang: true },
  { key: 'mixType', labelKey: 'qc.fields.mixType', type: 'select', lookup: 'qcMix' },
  { key: 'productName', labelKey: 'qc.fields.productName' },
  { key: 'ply', labelKey: 'qc.fields.ply', type: 'select', lookup: 'qcPly' },
  { key: 'color', labelKey: 'qc.fields.color', type: 'select', lookup: 'qcColors' },
  { key: 'gsm', labelKey: 'cutter.label.gsm', type: 'number' },
  { key: 'widthMm', labelKey: 'qc.fields.width', type: 'number' },
  { key: 'quantityKg', labelKey: 'common.quantity', type: 'number' },
  { key: 'producedKg', labelKey: 'production.fields.produced', type: 'number' },
  { key: 'wastePercent', labelKey: 'production.fields.waste', type: 'number' },
  { key: 'expectedFinish', labelKey: 'production.fields.expectedFinish', type: 'date' },
  { key: 'status', labelKey: 'common.status', type: 'select', options: keysToOptions('production.status.', ['open', 'in-progress', 'completed', 'late', 'stopped']) },
];
