/**
 * Global-search registry of every sub-module (tab) and the module route
 * that hosts it. Labels are translation keys, matched in any language.
 */
export interface SubModuleTarget {
  route: string;
  tab: string;
  labelKey: string;
}

export const SUB_MODULES: SubModuleTarget[] = [
  { route: '/cutter', tab: 'rolls', labelKey: 'cutter.tabs.rolls' },
  { route: '/cutter', tab: 'specs', labelKey: 'cutter.tabs.specs' },
  { route: '/warehouse', tab: 'warehouses', labelKey: 'warehouse.tabs.warehouses' },
  { route: '/warehouse', tab: 'items', labelKey: 'warehouse.tabs.items' },
  { route: '/warehouse', tab: 'movements', labelKey: 'warehouse.tabs.movements' },
  { route: '/quality', tab: 'dasht', labelKey: 'quality.tabs.dasht' },
  { route: '/quality', tab: 'materials', labelKey: 'quality.tabs.materials' },
  { route: '/quality', tab: 'chemicals', labelKey: 'quality.tabs.chemicals' },
  { route: '/quality', tab: 'maintenance', labelKey: 'quality.tabs.maintenance' },
  { route: '/production', tab: 'orders', labelKey: 'production.tabs.orders' },
  { route: '/chemicals', tab: 'output', labelKey: 'chemicals.tabs.output' },
  { route: '/chemicals', tab: 'staff', labelKey: 'chemicals.tabs.staff' },
  { route: '/chemicals', tab: 'rawPurchases', labelKey: 'chemicals.tabs.rawPurchases' },
  { route: '/chemicals', tab: 'opPurchases', labelKey: 'chemicals.tabs.opPurchases' },
  { route: '/sales', tab: 'workOrders', labelKey: 'sales.tabs.workOrders' },
  { route: '/sales', tab: 'exportOrders', labelKey: 'sales.tabs.exportOrders' },
  { route: '/sales', tab: 'invoices', labelKey: 'sales.tabs.invoices' },
  { route: '/sales', tab: 'customers', labelKey: 'sales.tabs.customers' },
  { route: '/sales', tab: 'statement', labelKey: 'sales.tabs.statement' },
  { route: '/purchasing', tab: 'requests', labelKey: 'purchasing.tabs.requests' },
  { route: '/purchasing', tab: 'quotations', labelKey: 'purchasing.tabs.quotations' },
  { route: '/purchasing', tab: 'orders', labelKey: 'purchasing.tabs.orders' },
  { route: '/purchasing', tab: 'suppliers', labelKey: 'purchasing.tabs.suppliers' },
  { route: '/logistics', tab: 'imports', labelKey: 'logistics.tabs.imports' },
  { route: '/logistics', tab: 'exports', labelKey: 'logistics.tabs.exports' },
  { route: '/finance', tab: 'accounts', labelKey: 'finance.tabs.accounts' },
  { route: '/finance', tab: 'journal', labelKey: 'finance.tabs.journal' },
  { route: '/finance', tab: 'banks', labelKey: 'finance.tabs.banks' },
  { route: '/finance', tab: 'pnl', labelKey: 'finance.tabs.pnl' },
  { route: '/finance', tab: 'balanceSheet', labelKey: 'finance.tabs.balanceSheet' },
  { route: '/finance', tab: 'expenses', labelKey: 'finance.tabs.expenses' },
  { route: '/finance', tab: 'currencies', labelKey: 'finance.tabs.currencies' },
  { route: '/hr', tab: 'employees', labelKey: 'hr.tabs.employees' },
  { route: '/hr', tab: 'attendance', labelKey: 'hr.tabs.attendance' },
  { route: '/hr', tab: 'leaves', labelKey: 'hr.tabs.leaves' },
  { route: '/hr', tab: 'penalties', labelKey: 'hr.tabs.penalties' },
  { route: '/hr', tab: 'performance', labelKey: 'hr.tabs.performance' },
  { route: '/hr', tab: 'managerReviews', labelKey: 'hr.tabs.managerReviews' },
  { route: '/hr', tab: 'zk', labelKey: 'hr.tabs.zkSync' },
  { route: '/administration', tab: 'documents', labelKey: 'administration.tabs.documents' },
  { route: '/administration', tab: 'fleet', labelKey: 'administration.tabs.fleet' },
  { route: '/administration', tab: 'custody', labelKey: 'administration.tabs.custody' },
  { route: '/administration', tab: 'contracts', labelKey: 'administration.tabs.contracts' },
  { route: '/administration', tab: 'permits', labelKey: 'administration.tabs.permits' },
  { route: '/administration', tab: 'safetyCerts', labelKey: 'safety.tabs.certificates' },
  { route: '/safety', tab: 'certificates', labelKey: 'safety.tabs.certificates' },
  { route: '/safety', tab: 'insurance', labelKey: 'safety.tabs.insurance' },
  { route: '/clinic', tab: 'visits', labelKey: 'clinic.tabs.visits' },
  { route: '/clinic', tab: 'clinics', labelKey: 'clinic.tabs.clinics' },
  { route: '/clinic', tab: 'doctors', labelKey: 'clinic.tabs.doctors' },
  { route: '/clinic', tab: 'medicines', labelKey: 'clinic.tabs.medicines' },
  { route: '/clinic', tab: 'dispenses', labelKey: 'clinic.tabs.dispenses' },
  { route: '/reports', tab: 'commercial', labelKey: 'reports.categories.commercial' },
  { route: '/reports', tab: 'operations', labelKey: 'reports.categories.operations' },
  { route: '/reports', tab: 'finance', labelKey: 'reports.categories.finance' },
  { route: '/reports', tab: 'people', labelKey: 'reports.categories.people' },
  { route: '/reports', tab: 'facility', labelKey: 'reports.categories.facility' },
  { route: '/reports', tab: 'chemicals', labelKey: 'reports.categories.chemicals' },
  { route: '/appearance', tab: 'theme', labelKey: 'appearance.tabs.theme' },
  { route: '/appearance', tab: 'translations', labelKey: 'appearance.tabs.translations' },
  { route: '/appearance', tab: 'languages', labelKey: 'appearance.tabs.languages' },
  { route: '/system', tab: 'audit', labelKey: 'system.tabs.audit' },
  { route: '/system', tab: 'lookups', labelKey: 'system.tabs.lookups' },
  { route: '/system', tab: 'switches', labelKey: 'system.tabs.switches' },
];
