/** Generated by tools/gen-warehouse-seed.py — do not edit. */
import { LookupValue } from '../../../core/models/system.models';
import { TRANSLATIONS } from '../i18n';

const lk = (
  id: string,
  group: string,
  value: string,
  labelAr: string,
  labelEn: string,
  parentValue?: string,
): LookupValue => {
  TRANSLATIONS['ar'][value] = labelAr;
  TRANSLATIONS['en'][value] = labelEn;
  return { id, group, value, labelAr, labelEn, parentValue };
};

export const SEED_ITEM_GROUPS: LookupValue[] = [
  lk('lv-ig-oilSeal', 'itemGroups', 'itemGroups.oilSeal', 'اويل سيل', 'Oil Seal'),
  lk('lv-ig-plumbing', 'itemGroups', 'itemGroups.plumbing', 'سباكة', 'Plumbing'),
  lk('lv-ig-belts', 'itemGroups', 'itemGroups.belts', 'سيور', 'Belts'),
  lk('lv-ig-screws', 'itemGroups', 'itemGroups.screws', 'مسامير+فولة غاطسة', 'Screws & Countersunk Washers'),
  lk('lv-ig-ledgers', 'itemGroups', 'itemGroups.ledgers', 'دفاتر', 'Stationery'),
  lk('lv-ig-oils', 'itemGroups', 'itemGroups.oils', 'زيوت + شحوم', 'Oils & Grease'),
  lk('lv-ig-bearings', 'itemGroups', 'itemGroups.bearings', 'رولمان بلى', 'Ball Bearings'),
  lk('lv-ig-mfgMaterials', 'itemGroups', 'itemGroups.mfgMaterials', 'خامات للتصنيع', 'Manufacturing Materials'),
  lk('lv-ig-campaign', 'itemGroups', 'itemGroups.campaign', 'الحملة', 'Campaign'),
  lk('lv-ig-safety', 'itemGroups', 'itemGroups.safety', 'الامن الصناعي', 'Industrial Safety'),
  lk('lv-ig-paints', 'itemGroups', 'itemGroups.paints', 'دهانات', 'Paints'),
  lk('lv-ig-electrical', 'itemGroups', 'itemGroups.electrical', 'الكهرباء', 'Electrical'),
  lk('lv-ig-mechanical', 'itemGroups', 'itemGroups.mechanical', 'الميكانيكا', 'Mechanical'),
  lk('lv-ig-air', 'itemGroups', 'itemGroups.air', 'الهواء', 'Air'),
  lk('lv-ig-hall', 'itemGroups', 'itemGroups.hall', 'الصالة', 'Production Floor'),
  lk('lv-ig-tools', 'itemGroups', 'itemGroups.tools', 'عدد وادوات', 'Tools & Equipment'),
];

export const SEED_ITEM_SUBGROUPS: LookupValue[] = [
  lk('lv-is-contactor', 'itemSubGroups', 'itemSubGroups.contactor', 'كونتاكتور', 'Contactor', 'itemGroups.electrical'),
  lk('lv-is-fuse', 'itemSubGroups', 'itemSubGroups.fuse', 'فيوز', 'Fuse', 'itemGroups.electrical'),
  lk('lv-is-switches', 'itemSubGroups', 'itemSubGroups.switches', 'مفاتيح', 'Switches', 'itemGroups.electrical'),
  lk('lv-is-lamps', 'itemSubGroups', 'itemSubGroups.lamps', 'لمبات+كشافات', 'Lamps & Floodlights', 'itemGroups.electrical'),
  lk('lv-is-cables', 'itemSubGroups', 'itemSubGroups.cables', 'كابلات', 'Cables', 'itemGroups.electrical'),
  lk('lv-is-devices', 'itemSubGroups', 'itemSubGroups.devices', 'اجهزة كهرياء+حساسات', 'Electrical Devices & Sensors', 'itemGroups.electrical'),
  lk('lv-is-relay', 'itemSubGroups', 'itemSubGroups.relay', 'ريلاي+اوفر لود', 'Relay & Overload', 'itemGroups.electrical'),
  lk('lv-is-motors', 'itemSubGroups', 'itemSubGroups.motors', 'مواتير', 'Motors', 'itemGroups.electrical'),
  lk('lv-is-terminals', 'itemSubGroups', 'itemSubGroups.terminals', 'كوس+ترامل', 'Terminals', 'itemGroups.electrical'),
  lk('lv-is-elecMisc', 'itemSubGroups', 'itemSubGroups.elecMisc', 'متنوع كلاسك', 'Electrical Miscellaneous', 'itemGroups.electrical'),
  lk('lv-is-coupling', 'itemSubGroups', 'itemSubGroups.coupling', 'كوبلن', 'Coupling', 'itemGroups.mechanical'),
  lk('lv-is-rodBar', 'itemSubGroups', 'itemSubGroups.rodBar', 'تيش + بار', 'Rod & Bar', 'itemGroups.mechanical'),
  lk('lv-is-gaskets', 'itemSubGroups', 'itemSubGroups.gaskets', 'جوانات', 'Gaskets', 'itemGroups.mechanical'),
  lk('lv-is-weldWire', 'itemSubGroups', 'itemSubGroups.weldWire', 'سلك لحام', 'Welding Wire', 'itemGroups.mechanical'),
  lk('lv-is-flange', 'itemSubGroups', 'itemSubGroups.flange', 'فلانشة', 'Flange', 'itemGroups.mechanical'),
  lk('lv-is-cooler', 'itemSubGroups', 'itemSubGroups.cooler', 'كولر', 'Cooler', 'itemGroups.mechanical'),
  lk('lv-is-weldElbow', 'itemSubGroups', 'itemSubGroups.weldElbow', 'كوع لحام', 'Welding Elbow', 'itemGroups.mechanical'),
  lk('lv-is-weldReducer', 'itemSubGroups', 'itemSubGroups.weldReducer', 'مسلوب لحام', 'Welding Reducer', 'itemGroups.mechanical'),
  lk('lv-is-packing', 'itemSubGroups', 'itemSubGroups.packing', 'حشو', 'Packing', 'itemGroups.mechanical'),
  lk('lv-is-flexAir', 'itemSubGroups', 'itemSubGroups.flexAir', 'وصلات مرنة+قرب هواء', 'Flexible Connections & Air Tanks', 'itemGroups.mechanical'),
  lk('lv-is-mechSeal', 'itemSubGroups', 'itemSubGroups.mechSeal', 'ميكانيكل سيل+تيل', 'Mechanical Seal & Pins', 'itemGroups.mechanical'),
  lk('lv-is-pipes', 'itemSubGroups', 'itemSubGroups.pipes', 'مواسير', 'Pipes', 'itemGroups.mechanical'),
  lk('lv-is-ironware', 'itemSubGroups', 'itemSubGroups.ironware', 'حدايد', 'Ironware', 'itemGroups.mechanical'),
  lk('lv-is-lathe', 'itemSubGroups', 'itemSubGroups.lathe', 'مستلزمات مخرطة', 'Lathe Supplies', 'itemGroups.mechanical'),
  lk('lv-is-pumps', 'itemSubGroups', 'itemSubGroups.pumps', 'طلمبات', 'Pumps', 'itemGroups.mechanical'),
  lk('lv-is-hydraulic', 'itemSubGroups', 'itemSubGroups.hydraulic', 'مستلزمات هيدرولك', 'Hydraulic Supplies', 'itemGroups.mechanical'),
  lk('lv-is-valves', 'itemSubGroups', 'itemSubGroups.valves', 'محابس', 'Valves', 'itemGroups.mechanical'),
  lk('lv-is-mechMisc', 'itemSubGroups', 'itemSubGroups.mechMisc', 'متنوع ميكانيكا', 'Mechanical Miscellaneous', 'itemGroups.mechanical'),
  lk('lv-is-gauges', 'itemSubGroups', 'itemSubGroups.gauges', 'عدادات', 'Gauges', 'itemGroups.air'),
  lk('lv-is-airConn', 'itemSubGroups', 'itemSubGroups.airConn', 'وصلات هواء', 'Air Connections', 'itemGroups.air'),
  lk('lv-is-airDevices', 'itemSubGroups', 'itemSubGroups.airDevices', 'اجهزة هواء', 'Air Devices', 'itemGroups.air'),
  lk('lv-is-compressor', 'itemSubGroups', 'itemSubGroups.compressor', 'كمبروسر', 'Compressor', 'itemGroups.air'),
  lk('lv-is-quality', 'itemSubGroups', 'itemSubGroups.quality', 'الجودة', 'Quality', 'itemGroups.hall'),
  lk('lv-is-production', 'itemSubGroups', 'itemSubGroups.production', 'الانتاج', 'Production', 'itemGroups.hall'),
  lk('lv-is-prep', 'itemSubGroups', 'itemSubGroups.prep', 'التحضيرات', 'Preparations', 'itemGroups.hall'),
  lk('lv-is-handTools', 'itemSubGroups', 'itemSubGroups.handTools', 'عدد', 'Tools', 'itemGroups.tools'),
  lk('lv-is-equipment', 'itemSubGroups', 'itemSubGroups.equipment', 'ادوات', 'Equipment', 'itemGroups.tools'),
  lk('lv-is-bits', 'itemSubGroups', 'itemSubGroups.bits', 'بنط', 'Drill Bits', 'itemGroups.tools'),
];

export const SEED_STOCK_UNITS: LookupValue[] = [
  lk('lv-un-count', 'units', 'units.count', 'عدد', 'Count'),
  lk('lv-un-piece', 'units', 'units.piece', 'قطعة', 'Piece'),
  lk('lv-un-box', 'units', 'units.box', 'ك/ع', 'Carton'),
  lk('lv-un-liter', 'units', 'units.liter', 'لتر', 'Liter'),
  lk('lv-un-kg', 'units', 'units.kg', 'كجم', 'Kilogram'),
  lk('lv-un-ton', 'units', 'units.ton', 'طن', 'Ton'),
  lk('lv-un-cm', 'units', 'units.cm', 'سم', 'Centimetre'),
  lk('lv-un-m', 'units', 'units.m', 'متر', 'Metre'),
  lk('lv-un-pack', 'units', 'units.pack', 'باكو', 'Pack'),
  lk('lv-un-roll', 'units', 'units.roll', 'لفة', 'Roll'),
];
