/** Generated by tools/gen-warehouse-seed.py — do not edit. */
import { StockItem } from '../../../core/models/warehouse.models';
import { SEED_SPARE_01 } from './spare-items-01';
import { SEED_SPARE_02 } from './spare-items-02';
import { SEED_SPARE_03 } from './spare-items-03';
import { SEED_SPARE_04 } from './spare-items-04';
import { SEED_SPARE_05 } from './spare-items-05';
import { SEED_SPARE_06 } from './spare-items-06';
import { SEED_SPARE_07 } from './spare-items-07';
import { SEED_SPARE_08 } from './spare-items-08';
import { SEED_SPARE_09 } from './spare-items-09';
import { SEED_SPARE_10 } from './spare-items-10';
import { SEED_SPARE_11 } from './spare-items-11';
import { SEED_SPARE_12 } from './spare-items-12';
import { SEED_SPARE_13 } from './spare-items-13';
import { SEED_SPARE_14 } from './spare-items-14';
import { SEED_SPARE_15 } from './spare-items-15';
import { SEED_SPARE_16 } from './spare-items-16';
import { SEED_SPARE_17 } from './spare-items-17';
import { SEED_SPARE_18 } from './spare-items-18';
import { SEED_SPARE_19 } from './spare-items-19';
import { SEED_SPARE_20 } from './spare-items-20';
import { SEED_SPARE_21 } from './spare-items-21';
import { SEED_SPARE_22 } from './spare-items-22';
import { SEED_SPARE_23 } from './spare-items-23';
import { SEED_SPARE_24 } from './spare-items-24';
import { SEED_SPARE_25 } from './spare-items-25';
import { SEED_SPARE_26 } from './spare-items-26';
import { SEED_SPARE_27 } from './spare-items-27';
import { SEED_SPARE_28 } from './spare-items-28';
import { SEED_SPARE_29 } from './spare-items-29';
import { SEED_SPARE_30 } from './spare-items-30';
import { SEED_SPARE_31 } from './spare-items-31';
import { SEED_SPARE_32 } from './spare-items-32';
import { SEED_SPARE_33 } from './spare-items-33';
import { SEED_SPARE_34 } from './spare-items-34';
import { SEED_SPARE_35 } from './spare-items-35';

export const SEED_SPARE_ITEMS: StockItem[] = [
  ...SEED_SPARE_01,
  ...SEED_SPARE_02,
  ...SEED_SPARE_03,
  ...SEED_SPARE_04,
  ...SEED_SPARE_05,
  ...SEED_SPARE_06,
  ...SEED_SPARE_07,
  ...SEED_SPARE_08,
  ...SEED_SPARE_09,
  ...SEED_SPARE_10,
  ...SEED_SPARE_11,
  ...SEED_SPARE_12,
  ...SEED_SPARE_13,
  ...SEED_SPARE_14,
  ...SEED_SPARE_15,
  ...SEED_SPARE_16,
  ...SEED_SPARE_17,
  ...SEED_SPARE_18,
  ...SEED_SPARE_19,
  ...SEED_SPARE_20,
  ...SEED_SPARE_21,
  ...SEED_SPARE_22,
  ...SEED_SPARE_23,
  ...SEED_SPARE_24,
  ...SEED_SPARE_25,
  ...SEED_SPARE_26,
  ...SEED_SPARE_27,
  ...SEED_SPARE_28,
  ...SEED_SPARE_29,
  ...SEED_SPARE_30,
  ...SEED_SPARE_31,
  ...SEED_SPARE_32,
  ...SEED_SPARE_33,
  ...SEED_SPARE_34,
  ...SEED_SPARE_35,
];
