/** Generated by tools/gen-warehouse-seed.py — do not edit. */
import { StockItem } from '../../../core/models/warehouse.models';
import { stock } from './warehouse-items.util';

export const SEED_SUPPLY_ITEMS: StockItem[] = [
  stock('SPL-001', 'استرتش', 'استرتش', 'wh-supplies', '', '', 'units.ton'),
  stock('SPL-002', 'كور 345سم', 'كور 345سم', 'wh-supplies', '', '', 'units.ton'),
  stock('SPL-003', 'علبة سلاح كتر', 'علبة سلاح كتر', 'wh-supplies', '', '', 'units.count'),
  stock('SPL-004', 'طباشير ملون', 'طباشير ملون', 'wh-supplies', '', '', 'units.count'),
  stock('SPL-005', 'كور 250سم', 'كور 250سم', 'wh-supplies', '', '', 'units.ton'),
  stock('SPL-006', 'كور 345سم خاص MG', '345    MG', 'wh-supplies', '', '', 'units.ton'),
];
